# Generated by Django 5.0.6 on 2024-06-19 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userbankaccount_is_bankrupt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRupt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankrupt', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='is_bankrupt',
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='bankrupt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bankrupt'),
        ),
    ]
