# Generated by Django 5.0.6 on 2024-06-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankrupt_remove_userbankaccount_is_bankrupt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='bankrupt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='BankRupt',
        ),
    ]
