# Generated by Django 5.0.6 on 2024-06-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bankrupt_alter_userbankaccount_bankrupt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='bankrupt',
        ),
        migrations.DeleteModel(
            name='BankRupt',
        ),
    ]
