# Generated by Django 5.0.6 on 2024-06-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_is_bankrupt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_bankrupt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
